services:

  alloy:
    image: grafana/alloy:latest
    container_name: event-observability-alloy

    command:
      - otel
      - --config=file:/etc/alloy/otel-config.yaml

    volumes:
      - ./otel-config.yaml:/etc/alloy/otel-config.yaml:ro

      - /Users/manojsingh/workspace/kafka-observability-grafana/logs:/var/log/order-service:ro

    ports:
      - "12345:12345"

    networks:
      - infra_default

networks:
  infra_default:
    external: true