services:

  alloy:
    image: grafana/alloy:latest
    container_name: event-observability-alloy

    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy

    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro

      # IMPORTANT:
      # Replace the host path below with the actual
      # absolute path to your order-service/logs directory.
      - /Users/manojsingh/workspace/kafka-observability-grafana/logs:/var/log/order-service:ro

    ports:
      - "12345:12345"

    networks:
      - infra_default

networks:
  infra_default:
    external: true